Edit and Remove Assessments (Frontend)
socialsoftware/humanaethica pull request #93
Opened 2024-06-14 18:26 UTC by joaogreg

2024-06-16 18:24 UTC, ritosilva requested changes
Do the resquested changes.

2024-06-16 18:24 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/webservice/UpdateAssessmentWebServiceIT.groovy
> +class UpdateAssessmentWebServiceIT extends SpockTest {
write a test for a volunteer that did not write de assessment

2024-06-16 18:24 UTC, ritosilva commented on frontend/tests/e2e/specs/assessments/edit_and_delete_assessment.js
> +describe('Edit Assessment', () => {
include as tests of assessment.ts and remove this file

2024-06-19 18:57 UTC, joaogreg commented on backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/AssessmentController.java
> +        int userId = ((AuthUser) ((Authentication) principal).getPrincipal()).getUser().getId();
It's being used in frontend/src/services/RemoteServices.ts:654

2024-06-21 10:19 UTC, ritosilva commented on backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/AssessmentController.java
> +        int userId = ((AuthUser) ((Authentication) principal).getPrincipal()).getUser().getId();
"int userId" is not being used

2024-06-21 10:31 UTC, ritosilva commented on backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/AssessmentController.java
> +        int userId = ((AuthUser) ((Authentication) principal).getPrincipal()).getUser().getId();
I've changed it.

2024-06-21 10:31 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/domain/UpdateAssessmentMethodTest.groovy
> +class UpdateAssessmentMethodTest extends SpockTest {
OK

2024-06-21 10:32 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/service/CreateAssessmentServiceTest.groovy
> +                THREE_DAYS_AGO,TWO_DAYS_AGO,ONE_DAY_AGO,null)
Still open

2024-06-21 10:32 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/service/GetAssessmentsByInstitutionServiceTest.groovy
> +                THREE_DAYS_AGO, TWO_DAYS_AGO, ONE_DAY_AGO,null)
Still open

2024-06-21 10:33 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/webservice/CreateAssessmentWebServiceIT.groovy
Still open

2024-06-21 10:33 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/webservice/GetAssessmentsByInstitutionWebServiceIT.groovy
> +                THREE_DAYS_AGO,TWO_DAYS_AGO, ONE_DAY_AGO, null)
Still open

2024-06-21 10:34 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/service/DeleteAssessmentServiceTest.groovy
> +class DeleteAssessmentServiceTest extends SpockTest {
Still open

2024-06-21 10:34 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/service/UpdateAssessmentServiceTest.groovy
> +class UpdateAssessmentServiceTest extends SpockTest {
Still open

2024-06-21 10:35 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/webservice/DeleteAssessmentWebServiceIT.groovy
> +class DeleteAssessmentWebServiceIT extends SpockTest {
Still open

2024-06-21 10:35 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/webservice/DeleteAssessmentWebServiceIT.groovy
> +class DeleteAssessmentWebServiceIT extends SpockTest {
Still open

2024-06-21 10:35 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/webservice/UpdateAssessmentWebServiceIT.groovy
> +class UpdateAssessmentWebServiceIT extends SpockTest {
Still open

2024-06-21 10:36 UTC, ritosilva commented on frontend/tests/e2e/specs/assessments/edit_and_delete_assessment.js
> +describe('Edit Assessment', () => {
Still open

2024-06-21 10:37 UTC, ritosilva commented
Most of the issues were not addressed

2024-06-24 10:39 UTC, ritosilva requested changes
Access control tests need to be fixed

2024-06-24 10:39 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/webservice/DeleteAssessmentWebServiceIT.groovy
> +        def otherMember = createMember(USER_1_NAME,USER_1_USERNAME,USER_1_PASSWORD,USER_1_EMAIL, AuthUser.Type.NORMAL, otherInstitution, User.State.APPROVED)
It is not a volunteer, it is a member

2024-06-24 10:39 UTC, ritosilva commented on backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/humanaethica/assessment/webservice/UpdateAssessmentWebServiceIT.groovy
> +        def otherMember = createMember(USER_1_NAME,USER_1_USERNAME,USER_1_PASSWORD,USER_1_EMAIL, AuthUser.Type.NORMAL, otherInstitution, User.State.APPROVED)
It is not a volunteer, it is a member

2024-06-26 10:27 UTC, merged